### ISSUE TITLE
Failed to run black formatter (when using std::chrono as a function parameter)

### ISSUE THREAD

**Issue by finger563** [pthom/litgen#12]
I'm having issues with functions that take parameters such as a `const std::chrono::duration<float> &period`:

```
error: cannot format /Users/bob/esp-cpp/espp/lib/python_bindings/espp_lib/__init__.pyi: Cannot parse: 1035:154: period: std.chrono.duration<float>
⛔️ Oh no! 💥 💔 💥
1 file failed to reformat.
WARNING:root:Failed to run black formatter on /Users/bob/esp-cpp/espp/lib/python_bindings/espp_lib/__init__.pyi
error: cannot format /Users/bob/esp-cpp/espp/lib/python_bindings/espp_lib/__init__.pyi: Cannot parse: 1035:154: period: std.chrono.duration<float>
⛔️ Oh no! 💥 💔 💥
1 file failed to reformat.
WARNING:root:Failed to run black formatter on /Users/bob/esp-cpp/espp/lib/python_bindings/espp_lib/__init__.pyi
error: cannot format /Users/bob/esp-cpp/espp/lib/python_bindings/espp_lib/__init__.pyi: Cannot parse: 1035:154: period: std.chrono.duration<float>
⛔️ Oh no! 💥 💔 💥
1 file failed to reformat.
WARNING:root:Failed to run black formatter on /Users/bob/esp-cpp/espp/lib/python_bindings/espp_lib/__init__.pyi
Traceback (most recent call last):
  File "/Users/bob/esp-cpp/espp/lib/autogenerate_bindings.py", line 135, in <module>
    autogenerate()
  File "/Users/bob/esp-cpp/espp/lib/autogenerate_bindings.py", line 126, in autogenerate
    litgen.write_generated_code_for_files(
  File "/Users/bob/esp-cpp/espp/lib/env/lib/python3.12/site-packages/litgen/litgen_generator.py", line 227, in write_generated_code_for_files
    generator.process_cpp_file(cpp_header)
  File "/Users/bob/esp-cpp/espp/lib/env/lib/python3.12/site-packages/litgen/litgen_generator.py", line 82, in process_cpp_file
    code = _read_code(self.lg_context.options, filename)
  File "/Users/bob/esp-cpp/espp/lib/env/lib/python3.12/site-packages/litgen/litgen_generator.py", line 282, in _read_code
    assert os.path.isfile(filename)
AssertionError
```

I've used pybind11 with these functions (manually) before using:

![CleanShot 2024-07-11 at 22 05 01@2x](https://github.com/user-attachments/assets/9c4dad2c-3126-4ab3-8fcc-5393cc9ed1bc)

It's likely that I'm not configuring something correctly, but I wanted to see if maybe there was some limitation with litgen I wasn't aware of.

Edit:
Relevant source code:
![CleanShot 2024-07-11 at 22 06 41@2x](https://github.com/user-attachments/assets/4149d3aa-f236-4adc-8490-70ee6811d4c5)

**Comment by finger563** [comment]
Similar error when the duration is in a config struct:
![CleanShot 2024-07-11 at 22 11 38@2x](https://github.com/user-attachments/assets/b891253f-137e-425f-b7a1-1866376d22a5)

**Comment by pthom** [comment]
Hello,

Here are several answers:

## How to disable the black formatter
Black is a tool that will simply format the Python stub code. You can disable it, temporarily or permanently 

See option [python_run_black_formatter](https://pthom.github.io/litgen/litgen_book/02_03_00_options.html?highlight=python_run_black_formatter)

## How to handle `std::chrono` types within litgen

The real reason you have this error is that the type std::chrono::duration<float> is not known by litgen. 
As such, the python function signature will expect a _**python** type equal to  `std::chrono::duration<float>`_. This type name is not syntactically correct in Python, which is the reason why the black formatter fails 

#### Local solution to your project

You could add a regex to options.type_replacements in order to provide a replacement for `std::chrono::duration<float>` which could be replaced by something like `MyPythonChronoDuration[float]`

#### Global solution

Inside cpp_options.py, [standard_type_replacements()](https://github.com/pthom/litgen/blob/226992d4e30be298963fa96e52254e2e45af6477/src/litgen/internal/cpp_to_python.py#L480-L541] could be adapted to handle chrono, since it seems like [pybind11 supports chrono](https://pybind11.readthedocs.io/en/stable/advanced/cast/chrono.html)

You could add this to this function:
```python
replacements_str = r"""
...
...
...
\bstd::map<\s*([\w:]*)\s*,\s*([\w:]*)\s*> -> Dict[\1, \2]

ADD THE LINE BELOW
\bstd::chrono::duration<.*> -> datetime.timedelta
....
```

As far as I understand you should also add something for time_point. I don't remember if this is a template type so it has to be done with care.


---

I'm always happy to have feedback about how users are using my projects, so that I'd be very interested to know in which context you are using litgen. Please give me some details. 

I took half an hour to answer your question, so please do take a few minutes to answer once you have tried these possibilities. 

Also, please consider posting a PR if you do find that the global solution works. 
In this case, you can test your work by adding tests inside https://github.com/pthom/litgen/blob/main/src/litgen/tests/internal/cpp_to_python_test.py

**Comment by finger563** [comment]
Thanks for the in-depth answer! That also helps with a few other types that I was having trouble with, such as `std::tuple`. If I understand you correctly, the python black formatter issues shouldn't affect the python binding in any way, so for initial testing (setting this up and making sure the bindings work) I can disable it, correct? If that works, then I'll make a PR with some updates like you suggested for types I'm using that are supported by pybind11 but not currently by litgen.

Regarding the project I'm using this for - it's principally https://github.com/esp-cpp/espp, which is a c++ library targeted towards embedded electronics using ESP32-series chips. That being said, we do a lot of test and integration development from host computers, so building many of our components into libraries (including python bindings) allows us to reuse types, serialization, event management, etc. across platforms such as Windows, MacOS, Android, and iOS. The python work for this is principally for allowing a configuration / test / debug interface but is also allows for other kinds of hobby applications in terms of remote C&C.

**Comment by pthom** [comment]
> If I understand you correctly, the python black formatter issues shouldn't affect the python binding in any way, so for initial testing (setting this up and making sure the bindings work) I can disable it, correct?

Absolutely this will only have effect the Python declarations (i.e. the *.pyi stub files), and only in a minor way which is the formatting. 

> If that works, then I'll make a PR with some updates like you suggested for types I'm using that are supported by pybind11 but not currently by litgen.

Thanks!
